[websites]

[websites.'pracuj.pl']
address = "https://it.pracuj.pl/praca"
enabled = false

[websites.'justjoin.it']
address = "https://justjoin.it/"
enabled = true

[websites.'OLX']
address = "https://www.olx.pl/praca/informatyka/"
enabled = false

[websites.'RocketJobs']
address = "https://rocketjobs.pl/"
enabled = false

[websites.'Solid.Jobs']
address = "https://solid.jobs/offers/it"
enabled = false

[properties]
level = ["junior"]
skills = ["python", "sql"]
